# The model configuration for a diffusion model, which includes various parameters and sub-configurations.

model:
  # Base learning rate for the model.
  base_learning_rate: 1.0e-4
  
  # The target model for the diffusion process.
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  
  # The parameters for the target model.
  params:
    # Parameterization method for the model.
    parameterization: "v"
    
    # The range of linear schedule for the model.
    linear_start: 0.00085
    linear_end: 
